import 'package:employee_application/Features/User/transactions_page/Data/Model/transactions_page_entity.dart';

final TransactionsPageEntity faktransactionsPageEntity =
    TransactionsPageEntity.fromJson({
      "message": "Success",
      "data": [
        {
          "transactionID": "TRX001",
          "transactionName": "طلب إجازة",
          "nameUserSubmaitTransaction": "محمد أحمد",
          "nationalId": "12345678901",
          "dateSubmaitTransaction": "2026-06-10",
          "dateReceiveTransaction": "2026-06-11",
          "dateEndTransaction": "2026-06-15",
          "statusTransaction": "1",
        },
        {
          "transactionID": "TRX002",
          "transactionName": "طلب نقل",
          "nameUserSubmaitTransaction": "أحمد علي",
          "nationalId": "98765432109",
          "dateSubmaitTransaction": "2026-06-08",
          "dateReceiveTransaction": "2026-06-09",
          "dateEndTransaction": null,
          "statusTransaction": '2',
        },
        {
          "transactionID": "TRX003",
          "transactionName": "طلب وثيقة",
          "nameUserSubmaitTransaction": "سارة خالد",
          "nationalId": "45678912345",
          "dateSubmaitTransaction": "2026-06-05",
          "dateReceiveTransaction": "2026-06-06",
          "dateEndTransaction": null,
          "statusTransaction": "3",
        },
        {
          "transactionID": "TRX004",
          "transactionName": "طلب تعديل بيانات",
          "nameUserSubmaitTransaction": "خالد محمود",
          "nationalId": "74185296300",
          "dateSubmaitTransaction": "2026-06-01",
          "dateReceiveTransaction": "2026-06-02",
          "dateEndTransaction": "2026-06-07",
          "statusTransaction": "4",
        },
        {
          "transactionID": "TRX005",
          "transactionName": "طلب اعتماد",
          "nameUserSubmaitTransaction": "ريم حسن",
          "nationalId": "15935748620",
          "dateSubmaitTransaction": "2026-05-28",
          "dateReceiveTransaction": "2026-05-29",
          "dateEndTransaction": "2026-06-03",
          "statusTransaction": "5",
        },
        {
          "transactionID": "TRX001",
          "transactionName": "طلب إجازة",
          "nameUserSubmaitTransaction": "محمد أحمد",
          "nationalId": "12345678901",
          "dateSubmaitTransaction": "2026-06-10",
          "dateReceiveTransaction": "2026-06-11",
          "dateEndTransaction": "2026-06-15",
          "statusTransaction": "6",
        },
        {
          "transactionID": "TRX002",
          "transactionName": "طلب نقل",
          "nameUserSubmaitTransaction": "أحمد علي",
          "nationalId": "98765432109",
          "dateSubmaitTransaction": "2026-06-08",
          "dateReceiveTransaction": "2026-06-09",
          "dateEndTransaction": null,
          "statusTransaction": '7',
        },
        {
          "transactionID": "TRX003",
          "transactionName": "طلب وثيقة",
          "nameUserSubmaitTransaction": "سارة خالد",
          "nationalId": "45678912345",
          "dateSubmaitTransaction": "2026-06-05",
          "dateReceiveTransaction": "2026-06-06",
          "dateEndTransaction": null,
          "statusTransaction": "3",
        },
        {
          "transactionID": "TRX004",
          "transactionName": "طلب تعديل بيانات",
          "nameUserSubmaitTransaction": "خالد محمود",
          "nationalId": "74185296300",
          "dateSubmaitTransaction": "2026-06-01",
          "dateReceiveTransaction": "2026-06-02",
          "dateEndTransaction": "2026-06-07",
          "statusTransaction": "4",
        },
        {
          "transactionID": "TRX005",
          "transactionName": "طلب اعتماد",
          "nameUserSubmaitTransaction": "ريم حسن",
          "nationalId": "15935748620",
          "dateSubmaitTransaction": "2026-05-28",
          "dateReceiveTransaction": "2026-05-29",
          "dateEndTransaction": "2026-06-03",
          "statusTransaction": "5",
        },
        {
          "transactionID": "TRX001",
          "transactionName": "طلب إجازة",
          "nameUserSubmaitTransaction": "محمد أحمد",
          "nationalId": "12345678901",
          "dateSubmaitTransaction": "2026-06-10",
          "dateReceiveTransaction": "2026-06-11",
          "dateEndTransaction": "2026-06-15",
          "statusTransaction": "1",
        },
        {
          "transactionID": "TRX001",
          "transactionName": "طلب إجازة",
          "nameUserSubmaitTransaction": "محمد أحمد",
          "nationalId": "12345678901",
          "dateSubmaitTransaction": "2026-06-10",
          "dateReceiveTransaction": "2026-06-11",
          "dateEndTransaction": "2026-06-15",
          "statusTransaction": "1",
        },
        {
          "transactionID": "TRX001",
          "transactionName": "طلب إجازة",
          "nameUserSubmaitTransaction": "محمد أحمد",
          "nationalId": "12345678901",
          "dateSubmaitTransaction": "2026-06-10",
          "dateReceiveTransaction": "2026-06-11",
          "dateEndTransaction": "2026-06-15",
          "statusTransaction": "1",
        },
        {
          "transactionID": "TRX001",
          "transactionName": "طلب إجازة",
          "nameUserSubmaitTransaction": "محمد أحمد",
          "nationalId": "12345678901",
          "dateSubmaitTransaction": "2026-06-10",
          "dateReceiveTransaction": "2026-06-11",
          "dateEndTransaction": "2026-06-15",
          "statusTransaction": "1",
        },
        {
          "transactionID": "TRX001",
          "transactionName": "طلب إجازة",
          "nameUserSubmaitTransaction": "محمد أحمد",
          "nationalId": "12345678901",
          "dateSubmaitTransaction": "2026-06-10",
          "dateReceiveTransaction": "2026-06-11",
          "dateEndTransaction": "2026-06-15",
          "statusTransaction": "1",
        },
        {
          "transactionID": "TRX001",
          "transactionName": "طلب إجازة",
          "nameUserSubmaitTransaction": "محمد أحمد",
          "nationalId": "12345678901",
          "dateSubmaitTransaction": "2026-06-10",
          "dateReceiveTransaction": "2026-06-11",
          "dateEndTransaction": "2026-06-15",
          "statusTransaction": "1",
        },
        {
          "transactionID": "TRX001",
          "transactionName": "طلب إجازة",
          "nameUserSubmaitTransaction": "محمد أحمد",
          "nationalId": "12345678901",
          "dateSubmaitTransaction": "2026-06-10",
          "dateReceiveTransaction": "2026-06-11",
          "dateEndTransaction": "2026-06-15",
          "statusTransaction": "1",
        },
        {
          "transactionID": "TRX001",
          "transactionName": "طلب إجازة",
          "nameUserSubmaitTransaction": "محمد أحمد",
          "nationalId": "12345678901",
          "dateSubmaitTransaction": "2026-06-10",
          "dateReceiveTransaction": "2026-06-11",
          "dateEndTransaction": "2026-06-15",
          "statusTransaction": "1",
        },
      ],
    });
