// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBshv0bG_OjVnCk9P5mwW75_qTQ1SzKVmI',
    appId: '1:1081497804318:web:eff1a961379cc6c236580f',
    messagingSenderId: '1081497804318',
    projectId: 'graduation-project-4083d',
    authDomain: 'graduation-project-4083d.firebaseapp.com',
    storageBucket: 'graduation-project-4083d.firebasestorage.app',
    measurementId: 'G-YLJXV9071L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRwdnQlQJ5wRAvX-SMF67If69nrr8GJOE',
    appId: '1:1081497804318:android:1e994605b3f0f07136580f',
    messagingSenderId: '1081497804318',
    projectId: 'graduation-project-4083d',
    storageBucket: 'graduation-project-4083d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQZpO8NNZ9aK5btxrE2t2Lh44uGMyxEyw',
    appId: '1:1081497804318:ios:f5c6816de15cd2eb36580f',
    messagingSenderId: '1081497804318',
    projectId: 'graduation-project-4083d',
    storageBucket: 'graduation-project-4083d.firebasestorage.app',
    iosBundleId: 'com.example.employeeApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQZpO8NNZ9aK5btxrE2t2Lh44uGMyxEyw',
    appId: '1:1081497804318:ios:f5c6816de15cd2eb36580f',
    messagingSenderId: '1081497804318',
    projectId: 'graduation-project-4083d',
    storageBucket: 'graduation-project-4083d.firebasestorage.app',
    iosBundleId: 'com.example.employeeApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBshv0bG_OjVnCk9P5mwW75_qTQ1SzKVmI',
    appId: '1:1081497804318:web:b5100722e09f180f36580f',
    messagingSenderId: '1081497804318',
    projectId: 'graduation-project-4083d',
    authDomain: 'graduation-project-4083d.firebaseapp.com',
    storageBucket: 'graduation-project-4083d.firebasestorage.app',
    measurementId: 'G-0TDDMGXM06',
  );
}